services:
    appsco_filesystem.adapter.local.filesystem:
        class: Appsco\FilesystemBundle\Adapter\Local\Filesystem

    appsco_filesystem.adapter.local:
        class: Appsco\FilesystemBundle\Adapter\Local\Local
        arguments:
            - @appsco_filesystem.adapter.local.filesystem
            - true
        tags:
            - { name: appsco_filesystem.adapter, alias: local }

    appsco_filesystem.filesystem:
        class: Appsco\FilesystemBundle\Service\FilesystemProvider